"use client"
// import type { Metadata } from "next";
import { AdminHeader } from "@/components/layout/admin-header";
import "@/styles/globals.css";
import { usePathname } from "next/navigation";

// export const metadata: Metadata = {
//   title: {
//     template: "%s | 管理者",
//     default: "管理者", // フォールバック
//   },
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isAdminTop = pathname === "/admin";
  return (
    <html lang="ja">
      <body className="antialiased min-h-screen flex flex-col">
        {!isAdminTop && <AdminHeader />}
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
