import type { Metadata } from "next";
import { AdminHeader } from "@/components/layout/admin-header";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className="antialiased min-h-screen flex flex-col">
        <AdminHeader />
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
